# -*- coding: utf-8 -*-
"""UNSUPERVISED-LEARNING-CLUSTERING-19.8-YAKUNIY-AMALIY-VAZIFA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRj2Wnrrjowm2bfAEiVGd89uHnIT4EFs

#**Unsupervised learning. Clustering**
# Mijozlarni xarajat turlariga qarab segmentlash

✔️ klasterlash;

✔️ maʼlumotlarni normallashtirish;

✔️ klaster tahlili;

✔️ vizualizatsiya

## **Dataset: Wholesale Customers Data**  
- **Manba:** [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/wholesale+customers)  
- **Hajmi:** **22 KB**
- **Format:** CSV  
- **Tavsif:** bu dataset **ulgurji savdo mijozlarini** xarajatlar bo‘yicha klasterlash uchun ishlatiladi.  
  U quyidagi xarajat kategoriyalarini o‘z ichiga oladi:  
  - **channel** (mijoz turi: 1 – HoReCa (mehmonxona, restoran, kafelar) yoki 2 – chakana savdo)  
  - **region** (hudud: 1 – Lisbon, 2 – Oporto, 3 – boshqa)  
  - **fresh** (yangi mahsulotlarga sarf qilingan summa)  
  - **milk** (sut mahsulotlariga sarf qilingan summa)  
  - **grocery** (oziq-ovqat mahsulotlariga sarf qilingan summa)  
  - **frozen** (muzlatilgan mahsulotlarga sarf qilingan summa)  
  - **Detergents_Paper** (kimyoviy tozalash va qog‘oz mahsulotlari)  
  - **delicassen** (delikates mahsulotlar)  

---

### **Vazifa: mijozlarni xarajat turlariga qarab segmentlash**  
Maqsad – **mijozlarni xarajat qiladigan mahsulotlar bo‘yicha klasterlash va marketologlarga tavsiyalar berish**  

---

### **Klasterlash bosqichlari**  
1) **Maʼlumotlarni tayyorlash**  
   - `Channel` va `Region` ustunlarini olib tashlang yoki kodlang.  
   - Har bir xarajat ustunini **normalizatsiya qiling**.  

2) **K-means klasterlashni amalga oshirish**  
   - K-means yordamida mijozlarni **xarajat qilish odatlari** bo‘yicha segmentlarga ajrating.  

3) **Natijalarni vizualizatsiya qilish**  
   - **Pairplot yoki scatter plot** yordamida klasterlarni ko‘rsating.  
   - Har bir segmentning xarajatlar bo‘yicha o‘rtacha qiymatini diagrammada aks ettiring.
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/Wholesale_customers_data.csv")
df.head()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
# %matplotlib inline

df.info()

df.drop(['Channel', 'Region'], axis=1, inplace=True)
df.head()

from sklearn.preprocessing import StandardScaler
X = df.values[:,0:6]
X = np.nan_to_num(X)
norm_data = StandardScaler().fit_transform(X)
norm_data

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, n_init=10)
    kmeans.fit(norm_data)
    wcss.append(kmeans.inertia_)  # WCSS ni saqlash

plt.plot(range(1, 11), wcss, marker='o')
plt.title('Elbow Method')
plt.xlabel('Klaster soni (K)')
plt.ylabel('WCSS')
plt.show()

from sklearn.metrics import silhouette_score
import numpy as np

silhouette_scores = []
for i in range(2, 11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(norm_data)
    silhouette_avg = silhouette_score(norm_data, cluster_labels)
    silhouette_scores.append(silhouette_avg)

plt.plot(range(2, 11), silhouette_scores, marker='o')
plt.title('Silhouette Score bo\'yicha Optimal K')
plt.xlabel('Klaster soni')
plt.ylabel('Silhouette Score')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
clusters = kmeans.fit_predict(norm_data)
df['Cluster'] = clusters

import seaborn as sns
sns.pairplot(df, hue='Cluster', palette='Set1')
plt.show()

cluster_means = df.groupby('Cluster')[['Fresh', 'Milk', 'Grocery', 'Frozen',
                                      'Detergents_Paper', 'Delicassen']].mean()
cluster_means.plot(kind='bar', figsize=(10,6))
plt.title('Klasterlar bo\'yicha o\'rtacha xarajatlar')
plt.ylabel('Normalizatsiya qilingan xarajatlar')
plt.xticks(rotation=0)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""# **xulosalar**
Eng muhim xulosalar (marketologlar uchun):

Fresh universal: Barcha klasterlarda (0,1,3) fresh yuqori – yangi mahsulotlar asosiy driver

Ikki katta segment (0 va 2) – umumiy oziq-ovqat mijozlari (70% bo'lishi mumkin)

Ixtisoslashgan segmentlar (1-Fresh, 3-Frozen) – maxsus takliflar kerak

Detergents faqat professional (cluster 2) – bu guruhga professional tozalash vositalari

# Tavsiyalar
- Cluster 0: "Oilaviy savat" – sut+grocery+fresh chegirmasi
- Cluster 1: "HoReCa Fresh" – ertalab yetkazib berish, premium fresh
- Cluster 2: "Biznes paket" – detergents + oziq-ovqat
- Cluster 3: "Tez tayyor" – frozen + fresh kolleksiyasi

# mijozlar xarajatlariga qarab:

Katta xarajatli (2,3) → 70% byudjet
- Premium chegirmalar (10-15%)
- Shaxsiy menejerlar
- Yetkazib berish bepul
- VIP kartalar

Kichik xarajatli (0,1) → 30% byudjet
- Miqdoriy chegirmalar (buy 2 get 1)
- SMS aksiyalar
- Katta ambalajlar

"""